# Generated by Django 4.2 on 2024-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast_menu', models.CharField(max_length=100)),
                ('lunch_menu_1', models.CharField(max_length=100)),
                ('lunch_menu_2', models.CharField(max_length=100)),
                ('lunch_menu_3', models.CharField(max_length=100)),
            ],
        ),
    ]
