# Generated by Django 4.2 on 2024-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast_menu', models.CharField(max_length=100)),
                ('lunch_menu_1', models.CharField(max_length=100)),
                ('lunch_menu_2', models.CharField(max_length=100)),
                ('lunch_menu_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
