# Generated by Django 5.0.3 on 2024-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_dailymenu_delete_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('morning', 'Morning'), ('lunch', 'Lunch'), ('employee', 'Employee')], max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
    ]
