# Generated by Django 5.0.3 on 2024-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_unitmenu_like_count_usermeallike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
